plant_doctor/authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import RegisterView

urlpatterns = [
    path('login/', LoginView.as_view(template_name="authentication/login.html"), name="login"),
    path('logout/', LogoutView.as_view(template_name="authentication/logout.html"), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

plant_doctor/chat/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name="index"),
]

plant_doctor/core/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(("authentication.urls", "authentication"), namespace="auth")),
    path('chat/', include(("chat.urls", 'chat'), namespace="chat")),
    path('', RedirectView.as_view(url=reverse_lazy('chat:index'), permanent=False)),
]

plant_doctor/authentication/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from .mixins import TimestampMixin


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The given Email must be set")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password
        )
        
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user
    
    def create_staffuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password
        )
        
        user.is_staff = True
        user.save(using=self._db)

        return user



class User(AbstractBaseUser, PermissionsMixin, TimestampMixin):
    first_name = models.CharField(_("First Name"), max_length=50, blank=True, null=True)
    last_name = models.CharField(_("Last Name"), max_length=50, blank=True, null=True)
    email = models.EmailField(_("Email"), max_length=254, unique=True)
    is_staff = models.BooleanField(_("Is Staff"), default=False, help_text=_("Determines whether this user can login to the admin page."))
    is_active = models.BooleanField(_("Active"), help_text=_("Designates whether the user can login to the system."), default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_full_name(self) -> str:
        return str(self.first_name) + str(self.last_name)

plant_doctor/authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.password_validation import validate_password
from django.utils.translation import gettext_lazy as _

User = get_user_model()

class SignupForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password_2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError('This email is already taken')

        return email

    def clean_password(self):
        password = self.cleaned_data.get('password')
        validate_password(password)

        return password


    def clean(self):
        cleaned_data = super().clean()

        password = cleaned_data.get('password')
        password_2 = cleaned_data.get('password_2')

        if password is not None and password != password_2:
            raise forms.ValidationError('Passwords must match')

        return cleaned_data
    
    def save(self, commit):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password = forms.CharField(widget=forms.PasswordInput)
    password_2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email']

    def clean(self):
        '''
        Verify both passwords match.
        '''
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_2 = cleaned_data.get("password_2")
        if password is not None and password != password_2:
            self.add_error("password_2", "Your passwords must match")
        return cleaned_data

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField(
        label=_("Password"),
        help_text=_(
            "Raw passwords are not stored, so there is no way to see this "
            "user’s password, but you can change the password using "
            '<a href="../password">this form</a>.'
        ),
    )

    class Meta:
        model = User
        fields = ['email', 'password',]

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

plant_doctor/authentication/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model

from .forms import SignupForm

UserModel = get_user_model()

class RegisterView(CreateView):
    model = UserModel
    form_class = SignupForm
    template_name = "authentication/register.html"
    success_url = reverse_lazy('auth:login')

plant_doctor/chat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def home(req):
    return render(req, 'chat/index.html')

plant_doctor/templates/authentication/login.html
{% extends 'common/authentication/base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="login-box">
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="/" class="h1"><b>Plant</b><em>AI</em></a>
    </div>
    <div class="card-body">
      <p class="login-box-msg">Sign in to start your session</p>

      {% for error in form.non_field_errors %} {{ error }} {% endfor %}

      <form method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
          <input
            type="email"
            name="username"
            class="form-control"
            placeholder="Email"
          />
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input
            type="password"
            name="password"
            class="form-control"
            placeholder="Password"
          />
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="invalid-feedback">{{form.password.errors}}</div>
        </div>
        <div class="row mt-2">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember" />
              <label for="remember"> Remember Me </label>
            </div>
          </div>
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">
              Sign In
            </button>
          </div>
        </div>
      </form>

      <p class="mb-1 mt-3">
        <a href="#">I forgot my password</a>
      </p>
      <p class="mb-0">
        <a href="#" class="text-center">Register a new membership</a>
      </p>
    </div>
  </div>
</div>

{% endblock content %}

plant_doctor/templates/authentication/logout.html
{% extends 'common/authentication/base.html' %}

{% block title %}Logout{% endblock title %}

{% block content %}
    <div class="login-box">
      <div class="card card-outline card-primary">
        <div class="card-header text-center">
          <a href="/" class="h1"><b>Plant</b><em>AI</em></a>
        </div>
        <div class="card-body">
          <p class="login-box-msg">Successfully logged out</p>
        </div>
      </div>
    </div>
{% endblock content %}

plant_doctor/templates/authentication/register.html
{% extends 'common/authentication/base.html' %}

{% block title %}Register {% endblock title %}

{% block content %}
  <div class="login-box">
      <div class="card card-outline card-primary">
        <div class="card-header text-center">
          <a href="/" class="h1"><b>Plant</b><em>AI</em></a>
        </div>
        <div class="card-body">
          <p class="login-box-msg">Sign in to start your session</p>

          {% for error in form.non_field_errors %} {{ error }} {% endfor %}
    
          <form method="post">
            {% csrf_token %}
            <div class="input-group mb-3">
              <input name="email" type="email" class="form-control" placeholder="Email" value="{{ form.email.value }}">
              <div class="input-group-append">
                <div class="input-group-text">
                  <span class="fas fa-envelope"></span>
                </div>
              </div>
            </div>
            <div class="input-group mb-3">
              <input name="password" type="password" class="form-control" placeholder="Password">
              <div class="input-group-append">
                <div class="input-group-text">
                  <span class="fas fa-lock"></span>
                </div>
              </div>
            </div>
            <div class="input-group mb-3">
              <input name="password_2" type="password" class="form-control" placeholder="Confirm Password">
              <div class="input-group-append">
                <div class="input-group-text">
                  <span class="fas fa-lock"></span>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-4"></div>
              <div class="col-8">
                  <button type="submit" class="btn btn-primary btn-block">Sign up</button>
              </div>
            </div>
          </form>

          <p class="mb-0 mt-3">
            <a href="#" class="text-center">I already have a account</a>
          </p>
        </div>
      </div>
    </div>
{% endblock content %}

plant_doctor/templates/chat/index.html
{% extends 'common/chat/base.html' %}

{% block title %}Chat With Me{% endblock title %}

{% block content %}

    <nav class="main-header navbar navbar-expand navbar-dark">
        <a href="/" class="navbar-brand ml-5">
            <span class="brand-text font-weight-light"><b>Plant</b><em>AI</em></span>
        </a>
    
        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">

          <li class="nav-item mr-2">
            <a class="nav-link" href="{% url 'auth:logout' %}">
              <i class="fas fa-sign-out"></i>
            </a>
          </li>
        </ul>
      </nav>

    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="vstack gap-2">
                    <div class="p-2">First item</div>
                    <div class="p-2">Second item</div>
                    <div class="p-2">Third item</div>
                </div>                             
            </div>
            <div class="col-2"></div>
        </div>
        <div class="fixed-bottom bg-light">
            <div class="row">
                <hr>
                <div class="col-2"></div>
                <div class="col-8">
                    <div class="hstack gap-3  mb-3">
                        <textarea class="form-control" type="text" rows="1" placeholder="Send a message"></textarea>
                        <button type="submit" class="btn btn-secondary"><i class="far fa-paper-plane"></i></button>
                      </div>
                    <span class="mt-2"> 
                        <p><b>Plant</b><em>AI</em> is designed to help farmers diagnose and manage plant diseases effectively</p>
                    </span>
                </div>
                <div class="col-2"></div>
            </div>
        </div>
    </div>
{% endblock content %}

plant_doctor/templates/common/authentication/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/css/adminlte.min.css"/>
    <title>{% block title %}Plant AI{% endblock title %}</title>
</head>
<body class="hold-transition dark-mode login-page">
    {% block content %}
    {% endblock %}    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/js/bootstrap.min.js" ></script></body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/js/adminlte.min.js"></script>
</body>
</html>

plant_doctor/templates/common/chat/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/css/adminlte.min.css"/>
    <title>{% block title %}Plant AI{% endblock title %}</title>
</head>
<body class="hold-transition dark-mode layout-top-nav">
    {% block content %}
    {% endblock %}    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/js/bootstrap.min.js" ></script></body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/js/adminlte.min.js"></script>
</body>
</html>